name: Deploy on AWS
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create front-end env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_GENERATE_SOURCEMAP: false
          envkey_API_URL: "http://ec2-174-129-61-77.compute-1.amazonaws.com/api"
          directory: projeto-pancmap-front/
          file_name: .env
          fail_on_empty: true
      - name: Clean Docker
        run: docker system prune -a
      - name: Build process
        run: docker-compose build
      - name: Run app docker compose
        run: docker-compose down -v && docker-compose up -d
